name: Build latest
on:
  push:
    branches: main
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Version and Package
        run: |
          sed 's/^ *//' << END >> $GITHUB_ENV
              NEW_VERSION=v1.${{ github.run_number }}
              PACKAGE=tecolicom/texlive-pandoc-ja
          END

      # Build Docker Image
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#     - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
#         platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.PACKAGE }}:${{ env.NEW_VERSION }}
            ${{ env.PACKAGE }}:latest

      - name: Set Git Tag
        run: |
          git tag $NEW_VERSION
          git push --tags

